### ISSUE TITLE
Python3 : Nonlocals scope issue

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MatthieuDartiailh/enaml#5]
The following code fail to reach the ValueError after typing in the first field and hitting enter : 

``` enaml

from enaml.widgets.api import Window, Container, Field


enamldef Main(Window):

    attr aux = ''

    attr bis << str(aux)
    bis ::
        print(bis)

    attr ter << 2*aux
    ter ::
        print(ter)
        raise ValueError()

    Container:

        Field:
            text := aux
        Field:
            text << bis
        Field:
            text << ter
```

The traceback is the following :

```
dd
dddd
Traceback (most recent call last):
  File "/home/marul/Documents/enaml/enaml/qt/qt_field.py", line 147, in on_submit_text
    self._validate_and_apply()
  File "/home/marul/Documents/enaml/enaml/qt/qt_field.py", line 101, in _validate_and_apply
    d.text = text
  File "/home/marul/Documents/enaml/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/home/marul/Documents/enaml/enaml/core/expression_engine.py", line 210, in write
    pair.writer(owner, name, change)
  File "/home/marul/Documents/enaml/enaml/core/standard_handlers.py", line 120, in __call__
    call_func(func, (inverter, change['value']), {}, scope)
  File "py3_bug.enaml", line 21, in <module>
    text := aux
  File "/home/marul/Documents/enaml/enaml/core/standard_inverter.py", line 38, in load_name
    self.scope['nonlocals'][name] = value
KeyError: 'aux'

```

**Comment by sccolbert** [comment]
Does this fail on Python 2?

**Comment by MatthieuDartiailh** [comment]
No it does not.

**Comment by sccolbert** [comment]
Okay, so this could be an issue in Atom3, or Enaml3, correct?

**Comment by MatthieuDartiailh** [comment]
I just re-checked and on Python 2 I do get the expected ValueError. It seems that on Python 3 somewhere the original exception is lost. Looking at my debug prints it seems to be in atom but I never managed to reproduce in atom alone. If you have just a bit of time to look at it it would be great !

**Comment by sccolbert** [comment]
I'll try to take a look at this next week. I'm starting 2 weeks of vaca on Monday :)

**Comment by MatthieuDartiailh** [comment]
Thanks ! In the meantime I will keep digging ...

**Comment by MatthieuDartiailh** [comment]
Fixed in atom dev branch
